# Generated by Django 4.1.7 on 2023-03-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book', max_length=255)),
                ('description', models.TextField(help_text='A description of the book')),
                ('cover_image', models.ImageField(blank=True, help_text="An optional image of the book's cover", null=True, upload_to='covers/')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the book', max_digits=7)),
                ('published_on', models.DateTimeField(auto_now=True, help_text='The date and time the book was published')),
                ('published', models.BooleanField(default=True, help_text='A flag indicating whether the book is published')),
            ],
        ),
    ]
